services:
    rtmp:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: rtmp
        volumes:
            # - ./logs:/var/log/nginx
            # - ./syslogs:/var/log/syslog
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "1935:1935"
            - "443:443"
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: "certonly --webroot -w /var/www/certbot --force-renewal --email ${EMAIL} -d ${DOMAIN} --agree-tos"
    getcert:
        image: nginx:latest
        volumes:
            - cert.conf:/etc/nginx/nginx.conf:ro
            - ./certbot/conf:/etc/letsencrypt:rw
            - ./certbot/www:/var/www/certbot:rw
        ports:
            - "80:80"
            - "443:443"